### ISSUE TITLE
Mobile Social Buttons Not Showing - Revenue Loss Issue

### ISSUE THREAD

**Issue by jnorvi5** [jnorvi5/gorillacamping-#1]
# 🚨 URGENT: Mobile Social Buttons Missing - Killing Guerilla Growth

## Problem
The Facebook, Reddit, and TikTok social buttons are **NOT VISIBLE** on mobile devices. This is a **MAJOR revenue loss** because:
- Mobile users can't follow our social channels
- Lost viral potential on TikTok/Reddit 
- Reduced community building
- Missing out on guerilla-style organic growth

## Current Broken Code Location
File: `static/styles.css` around lines 600-700

The mobile responsive CSS is hiding the social buttons instead of making them mobile-friendly.

### 1. Fix Mobile Social Button Visibility
```css
/* MOBILE SOCIAL BUTTON FIXES */
@media (max-width: 768px) {
  .social-icons {
    display: flex !important;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    padding: 0 1rem;
  }
  
  .social-link {
    width: 280px;
    max-width: 90vw;
    justify-content: center;
    padding: 1rem 1.5rem;
    font-size: 1.1rem;
    text-align: center;
    display: flex !important;
    align-items: center;
    border: 2px solid;
    background: rgba(0,0,0,0.8);
    margin: 0.5rem 0;
    visibility: visible !important;
    opacity: 1 !important;
  }
  
  .social-icon {
    width: 24px;
    height: 24px;
    margin-right: 0.8rem;
    flex-shrink: 0;
  }
}
```

### 2. Force Button Visibility
```css
/* FORCE VISIBILITY ON ALL DEVICES */
.social-link, .share-btn {
  opacity: 1 !important;
  visibility: visible !important;
  display: flex !important;
}
```

### 3. Make Buttons Touch-Friendly
```css
.social-link {
  min-height: 48px; /* iOS/Android touch target minimum */
  touch-action: manipulation;
}
```

## Revenue Impact
- **Current Loss**: Every mobile visitor who can't follow = lost future sales
- **Potential Gain**: Mobile users are 70% of traffic = massive growth opportunity
- **Guerilla ROI**: This fix costs $0 but could increase social following by 300%

## Priority: 🔥 CRITICAL
This is blocking our path to $1,000/month goal. Mobile social growth = viral potential = affiliate revenue.

## Files to Update
- `static/styles.css` (main fix)
- Test on actual mobile devices
- Verify all social links work on mobile

## Success Metrics
- [ ] Social buttons visible on iPhone/Android
- [ ] Buttons are touch-friendly (48px minimum)
- [ ] All social links redirect properly on mobile
- [ ] Increased mobile social clicks in analytics
